/**
 * Report-generation orchestration: take a request, pull data, generate,
 * format, deposit in S3, mark complete, notify Platform.
 *
 * Retry semantics: each stage is idempotent to re-run (pulling data again,
 * generating again, uploading to the same deterministic S3 key again all
 * produce the same or a strictly improving result), so on failure the
 * whole request is retried from the top rather than resumed mid-pipeline.
 * The S3 key is versioned (v1, then v2 after the first Regenerate...) from
 * Platform's edit_attempts, so a retry rewrites the same version.
 * GenerationStateService caps this at MAX_GENERATION_ATTEMPTS (3, the queue's maxReceiveCount) and
 * marks the request failed rather than retrying forever.
 */

import { Inject, Injectable, Logger } from '@nestjs/common';
import type { AppEnv } from '../config/env';
import { APP_ENV } from '../config/config.module';
import { CompanionClient } from '../companion/companion.client';
import { ContentHubClient } from './packet/content-hub.client';
import type { ReportInputPacket } from './packet/report-packet.types';
import { ReportDocService } from './render/report-doc.service';
import { parseNarrative, type ExecutiveSummaryContent } from './content/executive-summary';
import { buildSurveyCharts } from './content/survey-charts';
import { ReportStorageService, reportVersion } from './storage/report-storage.service';
import { ReportReadyNotifier } from './notify/report-ready.service';
import { GenerationStateService } from './state/generation-state.service';
import { cleanTranscriptText, splitPrerecordedLivestream } from './preprocess/transcript';
import { TemplateStore } from './templates/template-store.service';
import { reportSurveyResponses } from './preprocess/survey';
import { pendingTranscripts } from './packet/transcript-wait';
import { ReportRequestQueue } from './queue/report-request-queue.service';

export const MACHINE_TRANSCRIPT_NOTE =
  "Transcripts are machine-generated by Zoom and may contain errors in names and terms.";

export interface ReportRequest {
  requestId: string;
  campaignId: string;
}

@Injectable()
export class ReportGenerationOrchestrator {
  private readonly logger = new Logger(ReportGenerationOrchestrator.name);

  constructor(
    private readonly contentHub: ContentHubClient,
    private readonly companion: CompanionClient,
    private readonly reportDoc: ReportDocService,
    private readonly storage: ReportStorageService,
    private readonly notifier: ReportReadyNotifier,
    private readonly state: GenerationStateService,
    private readonly templates: TemplateStore,
    private readonly queue: ReportRequestQueue,
    @Inject(APP_ENV) private readonly env: AppEnv,
  ) {}

  async handle(request: ReportRequest): Promise<void> {
    const { requestId } = request;

    let existing = await this.state.get(requestId, request.campaignId || undefined);
    if (!existing) {
      if (!request.campaignId) {
        throw new Error(`Request ${requestId} has no state row and no campaignId; cannot start`);
      }
      existing = await this.state.initialize(requestId, request.campaignId);
    }
    if (existing.status === 'complete') {
      this.logger.log(`Request ${requestId} already complete, skipping (idempotent redelivery)`);
      return;
    }

    const campaignId = existing.campaignId;
    const version = reportVersion(existing.editAttempts);

    try {
      await this.state.beginAttempt(requestId, 'pulling_data');
      const packet = await this.contentHub.fetchReportPacket({
        campaignId,
        windowStart: existing.windowStart,
        windowEnd: existing.windowEnd,
        sources: existing.sources,
        requestId,
      });

      // CPR-47: a recent session whose Zoom transcript hasn't landed yet. Wait
      // for it (re-check on a delay) instead of writing a thin report.
      const pending = pendingTranscripts(packet.sessions, new Date(), this.env.transcriptRecentHours);
      if (pending.length > 0) {
        const since = existing.waitingSince ? Date.parse(existing.waitingSince) : Date.now();
        const label = pending[0].title ?? 'this session';
        if (Date.now() - since >= this.env.transcriptWaitMaxMinutes * 60_000) {
          const hours = Math.round(this.env.transcriptWaitMaxMinutes / 60);
          await this.state.markFailed(
            requestId,
            `Zoom's transcript for "${label}" did not arrive within ${hours} hours. Generate again once it is available.`,
          );
          this.logger.warn(`Request ${requestId}: gave up waiting for transcript (${label})`);
          return;
        }
        await this.state.markWaiting(requestId);
        await this.queue.requeue(requestId, String(campaignId), this.env.transcriptRecheckSeconds);
        this.logger.log(
          `Request ${requestId}: waiting for ${pending.length} transcript(s), re-check in ${this.env.transcriptRecheckSeconds}s`,
        );
        return;
      }

      const { template, note: templateNote } = await this.templates.load(packet.template);

      await this.state.markStatus(requestId, 'generating');
      if (templateNote) this.logger.warn(`Request ${requestId}: ${templateNote}`);
      const content = await this.generateContent(packet, template.systemPrompt, requestId, version);

      await this.state.markStatus(requestId, 'rendering');
      const html = await this.reportDoc.renderExecutiveSummary(content, { htmlTemplate: template.html });

      await this.state.markStatus(requestId, 'uploading');
      const s3Key = await this.storage.uploadReport(String(campaignId), requestId, version, html, content);
      await this.state.markComplete(requestId, s3Key, version);

      this.logger.log(`Request ${requestId} complete: ${s3Key}`);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      this.logger.error(`Request ${requestId} failed: ${message}`);
      await this.state.markFailed(requestId, message);
      throw err;
    }

    // Outside the try: the report is complete, so a notify problem must not
    // mark it failed or retry the generation. The notifier never throws.
    await this.notifier.notify({ requestId, campaignId: String(campaignId), version });
  }

  /**
   * Assembles a report-generation prompt from the Content Hub packet and
   * calls cht-companion `/generate`. Filler-word cleaning and
   * pre-record/livestream split happen here. Hub already ETL'd the warehouse
   * copy; this path never queries Aurora or cht-platform-tool.
   */
  private async generateContent(
    packet: ReportInputPacket,
    systemPrompt: string,
    requestId: string,
    version: number,
  ): Promise<ExecutiveSummaryContent> {
    const cleanedSessions = packet.sessions.map((session) => {
      const cleaned = cleanTranscriptText(session.transcriptText ?? '');
      const { prerecorded, livestream } = splitPrerecordedLivestream(cleaned);
      return { ...session, prerecorded, livestream };
    });

    const hasLivestream = cleanedSessions.some((s) => s.livestream !== null);
    const hasPrerecorded = cleanedSessions.some((s) => s.prerecorded.trim().length > 0);
    const variant: ExecutiveSummaryContent['variant'] =
      hasPrerecorded && hasLivestream
        ? 'pre_record_and_webinar'
        : hasLivestream
          ? 'webinar_only'
          : 'pre_record_only';

    const transcriptContext = cleanedSessions
      .map(
        (s) =>
          `Session: ${s.title ?? s.platformToolProgramId ?? 'untitled'}${s.sessionDate ? ` (${s.sessionDate})` : ''}\n${s.prerecorded}${
            s.livestream ? `\n\nQ&A:\n${s.livestream}` : ''
          }`,
      )
      .join('\n\n---\n\n');

    const surveyAnswers = reportSurveyResponses(packet.surveyResponses);
    const surveyContext = surveyAnswers.map((answers) => JSON.stringify(answers)).join('\n');
    const platformContext = (packet.platformSlices ?? [])
      .map((slice) => `${slice.platform} ${slice.fetchDate} (${slice.status}): ${JSON.stringify(slice.rows)}`)
      .join('\n');
    const hubspotContext = packet.hubspotRawData ? JSON.stringify(packet.hubspotRawData) : '';

    const userContent = fitToLimit(
      [
        `Campaign: ${packet.campaignName ?? `Campaign ${packet.campaignId}`}`,
        `Post-event feedback survey responses (n=${surveyAnswers.length}):\n${surveyContext || 'none'}`,
        `Platform metrics:\n${platformContext || 'none'}`,
        `HubSpot:\n${hubspotContext || 'none'}`,
      ],
      `Transcripts:\n${transcriptContext || 'none'}`,
    );

    // Output budget comes from REPORT_MAX_OUTPUT_TOKENS (CompanionClient
    // default). No temperature: Claude Sonnet 5 on Bedrock rejects it.
    const result = await this.companion.generate({ systemPrompt, userContent });
    await this.storage.saveModelReply(String(packet.campaignId), requestId, version, result.text);
    this.logger.log(
      `Generation for campaign ${packet.campaignId}: ${result.finishReason}, tokens in=${result.tokensInput ?? '?'} out=${result.tokensOutput ?? '?'}, ${estimateCostUsd(result)}`,
    );
    if (result.finishReason === 'truncated') {
      // Never publish a cut-off report: fail this attempt so the job retries.
      throw new ReportGenerationTruncatedError(
        `Generation hit the output token budget (${result.tokensOutput ?? '?'} tokens) for campaign ${packet.campaignId}`,
      );
    }
    const narrative = parseNarrative(result.text);

    // Template availability is our concern, not the client's: keep it out of
    // the report's input-completeness note.
    const missingSources = Object.entries(packet.inputCompleteness)
      .filter(([source, v]) => source !== 'template' && v.status !== 'ok')
      .map(([source, v]) => `${source}: ${v.status}`);

    return {
      title: `Executive Summary: ${narrative.programTitle ?? packet.campaignName ?? `Campaign ${packet.campaignId}`}`,
      campaignName: packet.campaignName ?? `Campaign ${packet.campaignId}`,
      variant,
      sessions: packet.sessions.map((s) => ({ title: s.title, kind: s.kind, date: s.sessionDate })),
      narrative,
      surveyCharts: buildSurveyCharts(surveyAnswers),
      attendees: null,
      transcriptNote: cleanedSessions.some((s) => s.prerecorded.trim() || s.livestream)
        ? MACHINE_TRANSCRIPT_NOTE
        : null,
      inputCompletenessNote:
        missingSources.length > 0
          ? `The following sources were unavailable or incomplete when this report was generated: ${missingSources.join(', ')}.`
          : null,
    };
  }
}

/** cht-companion /generate caps user_content at 100,000 characters. */
export const USER_CONTENT_LIMIT = 100_000;

/**
 * Join the context blocks, trimming only the transcripts (the long part)
 * to stay under the companion limit. The cut is marked so the model knows.
 */
export function fitToLimit(headBlocks: string[], transcripts: string, limit = USER_CONTENT_LIMIT): string {
  const head = headBlocks.join('\n\n');
  const marker = '\n[Transcript truncated to fit the input limit.]';
  const room = limit - head.length - 2;
  const body = transcripts.length <= room ? transcripts : `${transcripts.slice(0, Math.max(0, room - marker.length))}${marker}`;
  return `${head}\n\n${body}`;
}

export class ReportGenerationTruncatedError extends Error {}

/** Claude Sonnet 5 list price: $2 per million input tokens, $10 per million output. */
export function estimateCostUsd(result: { tokensInput?: number; tokensOutput?: number }): string {
  if (result.tokensInput === undefined || result.tokensOutput === undefined) return 'cost unknown';
  const usd = (result.tokensInput * 2 + result.tokensOutput * 10) / 1_000_000;
  return `~$${usd.toFixed(3)}`;
}
