import { ReportDocService, SECTION_IDS, TRANSCRIPT_KOLS_NOTE } from './report-doc.service';
import type { ExecutiveSummaryContent, GeneratedNarrative } from '../content/executive-summary';

const narrative: GeneratedNarrative = {
  programTitle: 'HER2-Low Update',
  format: 'pre_recorded_and_live',
  executiveSummary: [{ claim: 'First-line choice now carries the most weight.', body: 'Faculty converged on it.' }],
  objectives: ['Review DESTINY-Breast06 outcomes'],
  kols: [{ name: 'Dr. VK Gadi', affiliation: 'University of Illinois Cancer Center' }],
  overview: ['A live podcast conversation.'],
  keyTakeaways: [{ claim: 'Testing is shifting.', body: 'Ultra-low is flagged routinely.' }],
  quotes: [{ text: 'It was surprising.', speaker: 'Dr. Yan' }],
  conversationSummary: [],
  hcpEngagementThemes: [{ theme: 'Re-testing', detail: 'HCPs asked when to re-biopsy.' }],
  questionSummaries: [],
  audienceInsights: [{ label: 'Highest curiosity', body: 'ADC sequencing.' }],
  conclusions: [{ claim: 'Make toxicity operational.', body: 'Comfort rises with playbooks.', recommendation: 'Ship a one-page algorithm.' }],
};

const content: ExecutiveSummaryContent = {
  title: 'Executive Summary: HER2-Low Update',
  campaignName: '[TEST] Podcast 2',
  variant: 'webinar_only',
  sessions: [{ title: 'Podcast 2', kind: 'webinar', date: '2026-05-01T17:00:00Z' }],
  narrative,
  surveyCharts: [
    { question: 'Practice setting', responses: 4, multiSelect: false, options: [{ label: 'Community', count: 3 }, { label: 'Academic', count: 1 }] },
  ],
  kols: narrative.kols,
  kolSource: 'transcript',
  attendees: null,
  inputCompletenessNote: 'The following sources were unavailable: hubspot: missing.',
};

describe('ReportDocService', () => {
  const service = new ReportDocService();

  it('renders a full document with the title and cover', async () => {
    const html = await service.renderExecutiveSummary(content);
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<title>Executive Summary: HER2-Low Update</title>');
    expect(html).toContain('<h1>HER2-Low Update</h1>');
    expect(html).toContain('<dd>Dr. VK Gadi</dd>');
    expect(html).toContain('May 1, 2026');
    expect(html).toContain('Pre-recorded conversation with live Q&amp;A');
  });

  it('renders sections in CPR-18 order and leaves out empty ones', async () => {
    const html = await service.renderExecutiveSummary(content);
    const order = ['Executive Summary</h2>', 'Program Objectives', 'Key Opinion Leaders', 'Key Takeaways', 'Specific Comments', 'Post Webinar Survey Results', 'Strategic Takeaways'];
    const positions = order.map((t) => html.indexOf(t));
    expect(positions.every((p) => p > 0)).toBe(true);
    expect([...positions].sort((a, b) => a - b)).toEqual(positions);
    expect(html).not.toContain('<h2>Summary of Conversation</h2>');
    expect(html).not.toContain('<h2>Attendees</h2>');
  });

  it('names the left-out sections in the input-completeness note', async () => {
    const html = await service.renderExecutiveSummary(content);
    expect(html).toContain('hubspot: missing');
    expect(html).toContain('Not included for lack of input data: Summary of Conversation, Question Summaries, Attendees.');
  });

  it('notes that transcripts are machine-generated when the report used them', async () => {
    const html = await new ReportDocService().renderExecutiveSummary({
      ...content,
      transcriptNote: 'Transcripts are machine-generated by Zoom and may contain errors in names and terms.',
    });
    expect(html).toContain('Input Completeness');
    expect(html).toContain('Transcripts are machine-generated by Zoom');
  });

  it('renders quotes, recommendations and a survey chart', async () => {
    const html = await service.renderExecutiveSummary(content);
    expect(html).toContain('<p>“It was surprising.”</p><cite>Dr. Yan</cite>');
    expect(html).toContain('<strong>Strategic recommendation:</strong> Ship a one-page algorithm.');
    expect(html).toContain('1. Practice setting');
    expect(html).toContain('4 responses');
    expect(html).toContain('75% (3)');
  });

  it('renders only the requested sections', async () => {
    const html = await service.renderExecutiveSummary(content, { sections: ['keyTakeaways'] });
    expect(html).toContain('<h2>Key Takeaways</h2>');
    expect(html).not.toContain('<h2>Program Objectives</h2>');
  });

  it('escapes model text', async () => {
    const html = await service.renderExecutiveSummary({
      ...content,
      narrative: { ...narrative, overview: ['<script>alert(1)</script> & more'] },
    });
    expect(html).not.toContain('<script>');
    expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt; &amp; more');
  });

  it('fills a custom template and keeps $ in content literal', async () => {
    const html = await service.renderExecutiveSummary(
      { ...content, narrative: { ...narrative, overview: ['Costs $1 and $& stays'] } },
      { htmlTemplate: '<article>{{cover}}{{sections}}{{inputCompleteness}}{{unknown}}</article>' },
    );
    expect(html.startsWith('<article>')).toBe(true);
    expect(html).toContain('Costs $1 and $&amp; stays');
    expect(html).toContain('{{unknown}}');
  });

  it('renders Hub KOLs without the transcript note', async () => {
    const html = await service.renderExecutiveSummary({
      ...content,
      kols: [{ name: 'Dr. Ana Ruiz', affiliation: 'MD, Dana-Farber' }],
      kolSource: 'hub',
    });
    expect(html).toContain('<li><strong>Dr. Ana Ruiz</strong><span>MD, Dana-Farber</span></li>');
    expect(html).toContain('<dd>Dr. Ana Ruiz</dd>');
    expect(html).not.toContain('Dr. VK Gadi');
    expect(html).not.toContain(TRANSCRIPT_KOLS_NOTE);
  });

  it('says when KOLs come from the recording', async () => {
    const html = await service.renderExecutiveSummary(content);
    expect(html).toContain(TRANSCRIPT_KOLS_NOTE);
  });

  it('renders the Attendees section with counts and no names', async () => {
    const html = await service.renderExecutiveSummary({
      ...content,
      attendees: {
        registered: 40,
        attended: 30,
        avgMinutesWatched: 42,
        bySpecialty: [{ label: 'Oncology', count: 20 }, { label: 'Not provided', count: 10 }],
        byInstitution: [{ label: 'Mayo Clinic', count: 5 }],
      },
    });
    expect(html).toContain('<h2>Attendees</h2>');
    expect(html).toContain('<dt>Registered</dt><dd>40</dd>');
    expect(html).toContain('<dt>Attended</dt><dd>30 (75% of registrants)</dd>');
    expect(html).toContain('<dt>Average minutes watched</dt><dd>42</dd>');
    expect(html).toContain('<tr><td>Oncology</td><td>20</td></tr>');
    expect(html).toContain('<tr><td>Mayo Clinic</td><td>5</td></tr>');
    expect(html).not.toContain('Not included for lack of input data: Summary of Conversation, Question Summaries, Attendees.');
  });

  it('replaces the empty Q&A sections with the Q&A capture note', async () => {
    const qaNote = 'Live Q&A capture is not available yet.';
    const html = await service.renderExecutiveSummary({
      ...content,
      qaNote,
      narrative: { ...narrative, hcpEngagementThemes: [], questionSummaries: [], audienceInsights: [] },
    });
    expect(html).toContain('Live Q&amp;A capture is not available yet.');
    expect(html).toContain('Not included for lack of input data: Summary of Conversation, Attendees.');
  });

  it('keeps the generic note when some Q&A sections rendered', async () => {
    const html = await service.renderExecutiveSummary({ ...content, qaNote: 'Live Q&A capture is not available yet.' });
    expect(html).not.toContain('Live Q&amp;A capture');
    expect(html).toContain('Not included for lack of input data: Summary of Conversation, Question Summaries, Attendees.');
  });

  it('exposes all 13 CPR-18 sections', () => {
    expect(SECTION_IDS).toHaveLength(13);
  });
});
